app: echo
language: python

url_root: "/"
static_dir: static
static_url: /static/
static_domain: /static
#static_domain: http://static.echo.com

#schemes:
#  - scheme: mysql
#    user: gateway
#    pass: gateway
#    host: 192.168.0.35
#    port: 3306
#    db: gateway
#    storm: store
#    sqlalchemy: session
#  - scheme: mysql
#    alias: pay
#    user: pay
#    pass: pay
#    host: 192.168.0.35
#    port: 3306
#    db: pay
#    sqlalchemy: paysession
#  - scheme: mysql
#    alias: wallet
#    user: wallet
#    pass: wallet
#    host: 192.168.0.36
#    port: 3306
#    db: wallet
#    sqlalchemy: wtsession

############################################
# SessionStore
# MemcachedSessionStore
############################################
#session_store: MemcachedSessionStore
session_store: RedisSessionStore

redis:
  prefix: echo
  #host: 192.168.0.36
  host: 127.0.0.1
  port: 6379
  password: test
  timeout: 5
  expire: 86400

############################################
# LOGGER
############################################
version: 1
formatters:
  simpleFormater:
    #format: '%(asctime)s - %(levelname)s: %(message)s'
    format: '[%(name)s %(levelname)1.1s %(asctime)s %(module)s:%(lineno)d] %(message)s'
    datefmt: '%Y-%m-%d %H:%M:%S'
  consoleFormatter:
    (): 'echo.logkit.ColoredConsoleFormatter'
    format: '[%(levelname)1.1s %(asctime)s %(module)s:%(lineno)d] %(message)s'
    datefmt: '%Y-%m-%d %H:%M:%S'

handlers:
  console:
    class: logging.StreamHandler
    formatter: consoleFormatter
    level: NOTSET
    stream: ext://sys.stdout
  file:
    class : echo.logkit.iTimedRotatingFileHandler
    formatter: simpleFormater
    level: INFO
    filename: /usr/api-root/logs/echo-static/echo-static/log/info.log
    when: D
  iError:
    class : echo.logkit.iTimedRotatingFileHandler
    formatter: simpleFormater
    level: INFO
    filename: /usr/api-root/logs/echo-static/echo-static/log/error.log
    when: D

loggers:
  logger:
    level: DEBUG
    handlers: [console]
  tornado:
    level: NOTSET
    handlers: [file]
  iError:
    level: NOTSET
    handlers: [iError]

root:
  level: INFO
  handlers: [console, file, iError]

log:
  path: /usr/api-root/logs/echo-static
env:
  svg_path: http://192.168.1.108:8186/pygal_js/javascripts/
